---
- hosts: all
  tasks:
   - name: Installs epel-release
     yum: pkg=epel-release state=installed update_cache=true
   - name: Installs nginx web server
     yum: pkg=nginx state=installed update_cache=true
     become: true
     notify:
       - start nginx

  handlers:
   - name: start nginx
     service: name=nginx state=started